name: we_link
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  hexcolor: ^3.0.1
  smooth_page_indicator: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.1
  shared_preferences: ^2.1.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_messaging: ^14.7.15
  cloud_firestore: ^4.15.4
  firebase_core_platform_interface: ^5.0.0
  firebase_storage: ^11.6.5
  image_picker: ^0.8.7+5
  google_fonts: ^4.0.4
  readmore: ^2.2.0
  chewie: ^1.5.0
  auto_orientation: ^2.3.1
  animated_splash_screen: ^1.3.0
  flutter_image_compress: ^2.0.3
  flutter_emoji: ^2.4.0
  flutter_local_notifications: ^14.0.0+2
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.7
  path_provider: ^2.0.15
  http: ^0.13.6
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  intl: ^0.18.1
  visibility_detector: ^0.4.0+2
  uuid: ^4.3.3
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  audioplayers: ^5.2.1
  get: ^4.6.6
  firebase_pagination: ^3.1.0
  animate_do: ^3.3.3
 # flutter_neumorphic: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true


  assets:
     - assets/icons/
     - assets/images/
     - assets/lottie/
     - assets/sounds/
     - assets/SVGs/

  fonts:
    - family: IconBroken
      fonts:
       - asset: assets/icons/icons.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

