// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdX8p5ZiA4NlXcFA5NA_5bzh-xRBpCLso',
    appId: '1:734442525184:android:3da3aeea7950675de5bee5',
    messagingSenderId: '734442525184',
    projectId: 'social-app-201c9',
    storageBucket: 'social-app-201c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemH_jfuDcYdrBlRQouw1cMySY05kKx4A',
    appId: '1:734442525184:ios:db708e3d1fa66e34e5bee5',
    messagingSenderId: '734442525184',
    projectId: 'social-app-201c9',
    storageBucket: 'social-app-201c9.appspot.com',
    androidClientId: '734442525184-hnm3fhrhjbpk31hup3mo2ctadgi1eq8h.apps.googleusercontent.com',
    iosClientId: '734442525184-hp9vtjabjg5n8vdg6abikk108ktah2tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
